

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
 
import java.io.File;
import java.util.ArrayList;
import java.util.List;
 
public class ReportGenerator {
 
    public static void generateCucumberReport() {
        // Location of your JSON file generated by Cucumber
        File reportOutputDirectory = new File("target/cucumber-html-reports");
        String jsonFilePath = "target/cucumber-reports/cucumber.json";
 
        // List of JSON files to include in report
        List<String> jsonFiles = new ArrayList<>();
        jsonFiles.add(jsonFilePath);
 
        // Set project details
        String projectName = "Cucumber BDD Automation";
 
        // Create configuration
        Configuration configuration = new Configuration(reportOutputDirectory, projectName);
        configuration.addClassifications("Platform", System.getProperty("os.name"));
        configuration.addClassifications("Browser", System.getProperty("browser", "chrome"));
        configuration.addClassifications("Java Version", System.getProperty("java.version"));
 
        // Generate the report
        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
    }
 
    public static void main(String[] args) {
        generateCucumberReport();
    }
}